site_name: EdgeCDN-X
site_url: https://edgecdn-x.github.io
theme:
  name: material
plugins:
  - tags
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - "Overview": index.md
  - "Architecture": architecture.md
  - "CRDs": crds.md
  - "Deployment":
      - "Control Plane": 
          - "ArgoCD": argocd.md
          - "Registering Locations": locations.md
          - "Core Components": core-components.md
          - "EdgeCDN-X Controller": edgecdnx-controller.md
      - "Routing":
          - "CoreDNS": coredns.md
          - "CoreDNS Deployment": coredns-deployment.md
          - "Consul Deployment": consul-deployment.md
          - "EdgeCDN-X Controller - Routing": edgecdnx-controller-router.md
      - "Caching":
          - "Prerequisites": cache-prerequisites.md
          - "Ingress NGINX": ingress-nginx.md
          - "EdgeCDN-X Controller - Caching": edgecdnx-controller-cache.md
          - "Secure Urls": secure-urls.md
  - "S3 Gateway": s3-gateway.md
  - "URL Signing": url-signing.md
  - "Tags": tags.md
  - "Contact": contact.md